#!/bin/bash
set -e

if [ ! -d $HOME/rust-analyzer ]; then
    git clone https://github.com/rust-analyzer/rust-analyzer.git $HOME/rust-analyzer
fi

pushd $HOME/rust-analyzer
git fetch -a
git checkout -B release origin/release
cargo xtask install --server
popd
