#!/bin/bash
set -e

if [[ ! -x $HOME/.cargo/bin/rustup ]]; then
    curl https://sh.rustup.rs -sSf | sh
fi

$HOME/.cargo/bin/rustup update
$HOME/.cargo/bin/rustup install nightly
# https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu.html
$HOME/.cargo/bin/rustup component add rustfmt rust-src clippy
$HOME/.cargo/bin/cargo install racer
