#!/bin/bash
set -e

if [[ ! -x $HOME/.cargo/bin/rustup ]]; then
    curl https://sh.rustup.rs -sSf | sh
fi

$HOME/.cargo/bin/rustup update
$HOME/.cargo/bin/rustup install nightly
$HOME/.cargo/bin/rustup component add rustfmt rust-src
$HOME/.cargo/bin/cargo install racer
