# Default Theme

if patched_font_in_use; then
  TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="⮂"
  TMUX_POWERLINE_SEPARATOR_LEFT_THIN="⮃"
  TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="⮀"
  TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="⮁"
else
  TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="◀"
  TMUX_POWERLINE_SEPARATOR_LEFT_THIN="❮"
  TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="▶"
  TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="❯"
fi

BASE00="241"
BASE01="240"
BASE0="244"

BASE1="245"
BASE2="254"
BASE3="230"

YELLOW="136"
ORANGE="166"
RED="160"
MAGENTA="125"
VIOLET="61"
BLUE="33"
CYAN="37"
GREEN="64"

TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR:-${BASE2}}
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR:-${BASE1}}

TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_RIGHT_THIN}
TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_LEFT_THIN}


# Format: segment_name background_color foreground_color [non_default_separator]

if [ -z $TMUX_POWERLINE_LEFT_STATUS_SEGMENTS ]; then
  TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
    "tmux_session_info ${BASE2} ${GREEN}" \
    # "hostname 33 0" \
    #"ifstat 30 255" \
    #"ifstat_sys 30 255" \
    "lan_ip ${BASE2} ${BLUE}" \
    "wan_ip ${BASE2} ${BLUE}" \
    "vcs_branch 29 88" \
    "vcs_compare 60 255" \
    "vcs_staged 64 255" \
    "vcs_modified 9 255" \
    "vcs_others 245 0" \
  )
fi

if [ -z $TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS ]; then
  TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
    #"earthquake 3 0" \
    "pwd ${BASE2} 211" \
    # "mailcount 9 255" \
    # "now_playing 234 37" \
    #"cpu 240 136" \
    # "load 237 167" \
    #"tmux_mem_cpu_load 234 136" \
    # "battery 137 127" \
    "weather ${BASE2} ${CYAN}" \
    #"rainbarf 0 0" \
    #"xkb_layout 125 117" \
    "date_day ${BASE2} ${YELLOW}" \
    "date ${BASE2} ${YELLOW} ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
    "time ${BASE2} ${YELLOW} ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
    #"utc_time 235 136 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
  )
fi
