[tools]
"aqua:moonrepo/moon" = "v1.41.8"
go = "latest"
"go:github.com/rogpeppe/godef" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
golangci-lint = "2.11.2"
node = "23.5.0"

[settings]
experimental = true
